{
 "title": "Firewall",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Zeit", "label": "s", "query": "15s,30s,60s,120s,240s,600s" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Actions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iptables\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n      r._measurement == \"firewall_log\" and\n      r._field == \"count\"\n      )\n  |> group(columns: [\"action\"])      \n  |> aggregateWindow(every: ${Zeit}, fn: sum, createEmpty: true)\n  |> yield(name: \"Test\")"
    }
   ]
  },
  {
   "title": "IP SRC->DST",
   "type": "logs",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "import \"timezone\"\ntimezone.location(name: \"Europe/Berlin\")\ntimezone.fixed(offset: 0h)\nfrom(bucket: \"iptables\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"firewall_log\")\n  |> filter(fn: (r) => contains(value: r[\"_field\"], set: [\"src\", \"dst\", \"dst_port\", \"action\"]))\n  |> limit(n: 50)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: \"\" + string(v: r.src) + \" > \" + string(v: r.dst) + \" | \" + string(v: r.dst_port) + \":\" + string(v: r.proto) + \" | \" + string(v: r.action),\n      dst: r.dst,\n      src: r.src,\n      dst_port: r.dst_port,\n      zeit: string(v: r._time)\n  }))\n  |> sort(columns: [\"_time\"], desc: true)\n"
    }
   ]
  },
  {
   "title": "Blocks TCP/UDP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"iptables\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"firewall_log\" and\n    r._field == \"count\"\n  )\n  |> group(columns: [\"proto\"])\n  |> aggregateWindow(every: ${Zeit} , fn: sum, createEmpty: true)\n  |> yield(name: \"blocked_ports\")"
    }
   ]
  },
  {
   "title": "TCP/UDP",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iptables\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"firewall_log\" and\n    r._field == \"count\"\n  )\n  |> group(columns: [\"proto\"])\n  |> aggregateWindow(every: ${Zeit}, fn: sum, createEmpty: false)\n  |> yield(name: \"blocked_ports\")"
    }
   ]
  },
  {
   "title": "Actions Circle",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iptables\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n      r._measurement == \"firewall_log\" and\n      r._field == \"count\"\n      )\n  |> group(columns: [\"action\"])      \n  |> aggregateWindow(every: ${Zeit}, fn: sum, createEmpty: true)\n  |> yield(name: \"Test\")"
    }
   ]
  }
 ]
}